# Generated by Django 6.0.6 on 2026-08-09 06:13

from django.db import migrations
 
 
def seed(apps, schema_editor):
    Author = apps.get_model("inventoryApp", "Author")
    Books = apps.get_model("inventoryApp", "Books")
 
    for i in range(1, 11):
        author = Author.objects.create(name=f"Author {i}", nationality="Pakistani")
        for j in range(1, 6):
            Books.objects.create(
                title=f"Book {i}-{j}",
                description="Seeded book",
                published_date="2000-01-01",
                author=author,
                available_copies=(j % 3) or 1,
            )
 
 
def unseed(apps, schema_editor):
    apps.get_model("inventoryApp", "Author").objects.all().delete()
    apps.get_model("inventoryApp", "Books").objects.all().delete()
 
class Migration(migrations.Migration):
    dependencies = [("inventoryApp", "0004_books_alter_borrowrecord_book_delete_book")]
    operations = [migrations.RunPython(seed, unseed)]