# Generated by Django 6.0.6 on 2026-08-09 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0005_seed_authors_and_books'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='books',
            table='inventoryApp_books',
        ),
    ]
