# Generated by Django 6.1 on 2026-08-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='member',
            field=models.BooleanField(default=False),
        ),
    ]
